export const ROUTES = {
  DASHBOARD: '/',
  PATIENTS: '/patients',
  APPOINTMENTS: '/appointments',
  ADMISSIONS: '/admissions',
  EMERGENCIES: '/emergencies',
  CONSULTATIONS: '/consultations',
  HOSPITALIZATION: '/hospitalization',
  OPERATING_ROOM: '/operating-room',
  RESUSCITATION: '/resuscitation',
  MATERNITY: '/maternity',
  LABORATORY: '/laboratory',
  IMAGING: '/imaging',
  PHARMACY: '/pharmacy',
  BLOOD_BANK: '/blood-bank',
  MEDICAL_STOCK: '/medical-stock',
  BIOMEDICAL: '/biomedical',
  DOCTORS: '/doctors',
  HR: '/hr',
  FINANCE: '/finance',
  AMBULANCES: '/ambulances',
  ARCHIVES: '/archives',
  REPORTS: '/reports',
  SETTINGS: '/settings',
  NOT_FOUND: '/404',
} as const;
