/**
 * /consultations routes — backed by ConsultationService.
 *
 * Schema alignment (consultationsTable):
 *  - id: UUID (not integer)
 *  - No `date` column: use scheduledAt / startedAt for date-based fields
 *  - patientId: UUID reference (not integer)
 *  - number: generated by ConsultationService as CONS-YYYY-NNNNN
 *  - reason / motif: `reason` is the DB column; `motif` is accepted as an alias
 */
import { Router } from "express";
import { consultationService } from "../services/consultation";
import type { AuthenticatedRequest } from "../middleware/requireAuth";
import type { ActorCtx } from "../repositories/types";
import type { DbConsultation } from "../repositories/consultation";

const router = Router();

function actor(req: AuthenticatedRequest): ActorCtx {
  return {
    userId:   req.auth?.userId ?? "system",
    userName: req.auth?.userId ?? "system",
    userRole: req.auth?.role   ?? "guest",
  };
}

/** Normalize legacy DB type values to the frontend ConsultationType enum. */
const TYPE_NORMALIZE: Record<string, string> = {
  consultation_externe: "ambulatoire",
  urgence:              "urgences",
  hospitalier:          "hospitalisation",
};

function normalizeType(raw: string): string {
  return TYPE_NORMALIZE[raw] ?? raw;
}

function mapConsultation(c: DbConsultation) {
  // Derive a date string from scheduledAt or startedAt
  const dateStr = c.scheduledAt
    ? c.scheduledAt.toISOString().slice(0, 10)
    : c.startedAt
    ? c.startedAt.toISOString().slice(0, 10)
    : new Date().toISOString().slice(0, 10);

  return {
    id:          c.id,
    number:      c.number,
    encounterId: c.encounterId ?? null,
    patientId:   c.patientId ?? `cons-${c.id}`,
    patientName: c.patientName,
    patientMpi:  c.patientMpi,
    doctorId:    c.doctorId ?? "system",
    doctorName:  c.doctorName,
    specialty:   c.specialty,
    serviceId:   c.serviceId ?? "system",
    serviceName: c.serviceName,
    siteId:      "site-1",
    siteName:    "Site Principal",
    date:        dateStr,
    scheduledAt: c.scheduledAt?.toISOString() ?? `${dateStr}T08:00:00.000Z`,
    startedAt:   c.startedAt?.toISOString(),
    endedAt:     c.endedAt?.toISOString(),
    duration:    c.duration ?? undefined,
    type:        normalizeType(c.type),
    origin:      c.origin,
    // motif is the primary name; reason is the DB column (kept as alias)
    motif:       c.reason,
    reason:      c.reason,
    status:      c.status,
    syncStatus:  c.syncStatus,
    diagnosis:   c.diagnosis ?? undefined,
    notes:       c.notes     ?? undefined,
    createdAt:   c.createdAt.toISOString(),
    updatedAt:   c.updatedAt.toISOString(),
    createdById: "system",
    medical:     { allergies: [], chronicDiseases: [], majorHistory: [] },
  };
}

/** GET /consultations */
router.get("/", async (req, res, next) => {
  try {
    const { search, status, type, origin, doctor, specialty, dateFrom, dateTo, patientId } =
      req.query as Record<string, string | undefined>;

    const result = await consultationService.list({ patientId: patientId || undefined, limit: 300 });
    let rows = result.data;

    if (search) {
      const q = search.toLowerCase();
      rows = rows.filter((c) =>
        [c.patientName, c.patientMpi, c.number, c.doctorName, c.reason, c.serviceName, c.specialty]
          .some((f) => f?.toLowerCase().includes(q)),
      );
    }
    if (status && status !== "all")    rows = rows.filter((c) => c.status === status);
    if (type   && type   !== "all")    rows = rows.filter((c) => c.type === type || normalizeType(c.type) === type);
    if (origin && origin !== "all")    rows = rows.filter((c) => c.origin === origin);
    if (doctor && doctor !== "all")    rows = rows.filter((c) => c.doctorName === doctor);
    if (specialty && specialty !== "all") rows = rows.filter((c) => c.specialty === specialty);
    if (dateFrom) {
      rows = rows.filter((c) => {
        const d = c.scheduledAt?.toISOString().slice(0, 10) ?? "";
        return d >= dateFrom;
      });
    }
    if (dateTo) {
      rows = rows.filter((c) => {
        const d = c.scheduledAt?.toISOString().slice(0, 10) ?? "";
        return d <= dateTo;
      });
    }

    res.json(rows.map(mapConsultation));
  } catch (err) {
    next(err);
  }
});

/** GET /consultations/:id — fetch one consultation by UUID */
router.get("/:id", async (req, res, next) => {
  try {
    const id = String(req.params.id).replace(/^db-/, "");
    const row = await consultationService.findById(id);
    if (!row) { res.status(404).json({ error: "Consultation not found" }); return; }
    res.json(mapConsultation(row));
  } catch (err) {
    next(err);
  }
});

/** POST /consultations — create a new consultation */
router.post("/", async (req: AuthenticatedRequest, res, next) => {
  try {
    const body = req.body as {
      patientName?: string;
      patientMpi?:  string;
      patientId?:   string;
      doctorName?:  string;
      doctorId?:    string;
      specialty?:   string;
      serviceName?: string;
      serviceId?:   string;
      scheduledAt?: string;
      type?:        string;
      origin?:      string;
      reason?:      string;  // DB column name
      motif?:       string;  // primary alias accepted from frontend
      encounterId?: string;  // real encounter UUID from emergency/API
      status?:      string;
      duration?:    number;
    };

    // Accept `motif` as primary field, `reason` as fallback alias
    const reason = body.motif ?? body.reason;

    if (!body.patientName || !body.doctorName || !reason) {
      res.status(400).json({ error: "patientName, doctorName and motif (or reason) are required" });
      return;
    }

    const consultation = await consultationService.create({
      patientId:   body.patientId   ?? null,
      patientName: body.patientName,
      patientMpi:  body.patientMpi  ?? `MPI-${Date.now()}`,
      doctorId:    body.doctorId    ?? null,
      doctorName:  body.doctorName,
      specialty:   body.specialty   ?? "Médecine générale",
      serviceId:   body.serviceId   ?? null,
      serviceName: body.serviceName ?? "Médecine générale",
      scheduledAt: body.scheduledAt ? new Date(body.scheduledAt) : new Date(),
      type:        (body.type   as any) ?? "consultation_externe",
      origin:      (body.origin as any) ?? "rdv",
      reason,
      encounterId: body.encounterId ?? null,
      status:      (body.status as any) ?? "en_attente",
      duration:    body.duration ?? null,
    }, actor(req));

    res.status(201).json(mapConsultation(consultation));
  } catch (err) {
    next(err);
  }
});

/** PATCH /consultations/:id — update consultation status */
router.patch("/:id", async (req: AuthenticatedRequest, res, next) => {
  try {
    // IDs may be bare UUIDs; strip any legacy `db-` prefix
    const id = String(req.params.id).replace(/^db-/, "");

    const { status } = req.body as { status?: string };
    if (!status) {
      res.status(400).json({ error: "status is required" });
      return;
    }

    const updated = await consultationService.updateStatus(id, status, actor(req));

    if (!updated) {
      res.status(404).json({ error: "Consultation not found" });
      return;
    }

    res.json(mapConsultation(updated));
  } catch (err) {
    next(err);
  }
});

export default router;
