/**
 * AdmissionRepository — CRUD for the admissions table.
 *
 * Key schema facts (checked against admissions.ts):
 *  - admissionNumber: text, not null (ADM-2026-0001) — generated by AdmissionService
 *  - type: admissionTypeEnum, not null
 *  - status: admissionStatusEnum, default "active"
 *  - serviceName / doctorName: text, not null
 *  - motif: text, not null
 *  - admissionDate: date (not null), admissionTime: text (not null)
 *  - actualDischargeDate / actualDischargeTime for discharge
 *  - dischargeType / dischargeNotes for discharge info
 *  - deletedBy: uuid (present)
 */
import { eq, and, isNull, desc, count } from "drizzle-orm";
import {
  db as globalDb, admissionsTable, type DbAdmission, type InsertAdmission,
} from "@workspace/db";
import { type TxContext, type QueryOptions, type PagedResult, paged, qb , safeUuid } from "./types";

export type { DbAdmission };

export interface AdmissionListOpts extends QueryOptions {
  patientId?:   string;
  status?:      string;
  siteId?:      string;
  encounterId?: string;
}

export interface DischargePayload {
  dischargeType:  string;
  dischargeNotes?: string;
  actualDischargeDate: string; // ISO date string YYYY-MM-DD
  actualDischargeTime?: string; // HH:MM
}

export class AdmissionRepository {
  constructor(private readonly db: typeof globalDb = globalDb) {}

  async findById(id: string, ctx?: Pick<TxContext, "tx">): Promise<DbAdmission | null> {
    const rows = await qb(this.db, ctx)
      .select().from(admissionsTable)
      .where(and(eq(admissionsTable.id, id), isNull(admissionsTable.deletedAt)))
      .limit(1);
    return rows[0] ?? null;
  }

  async findByEncounter(encounterId: string, ctx?: Pick<TxContext, "tx">): Promise<DbAdmission | null> {
    const rows = await qb(this.db, ctx)
      .select().from(admissionsTable)
      .where(and(eq(admissionsTable.encounterId, encounterId), isNull(admissionsTable.deletedAt)))
      .limit(1);
    return rows[0] ?? null;
  }

  async list(opts: AdmissionListOpts = {}): Promise<PagedResult<DbAdmission>> {
    const { patientId, status, siteId, encounterId, limit = 50, offset = 0, includeDeleted = false } = opts;
    const conditions = [];
    if (!includeDeleted) conditions.push(isNull(admissionsTable.deletedAt));
    if (patientId)   conditions.push(eq(admissionsTable.patientId, patientId));
    if (status)      conditions.push(eq(admissionsTable.status, status as any));
    if (siteId)      conditions.push(eq(admissionsTable.siteId, siteId));
    if (encounterId) conditions.push(eq(admissionsTable.encounterId, encounterId));

    const where = conditions.length ? and(...conditions) : undefined;
    const [rows, [{ total }]] = await Promise.all([
      this.db.select().from(admissionsTable).where(where)
        .orderBy(desc(admissionsTable.admissionDate)).limit(limit).offset(offset),
      this.db.select({ total: count() }).from(admissionsTable).where(where),
    ]);
    return paged(rows, Number(total), { limit, offset });
  }

  /** Count all admissions — used by AdmissionService to generate admissionNumber */
  async countAll(): Promise<number> {
    const [{ total }] = await this.db.select({ total: count() }).from(admissionsTable);
    return Number(total);
  }

  async create(data: InsertAdmission, ctx: TxContext): Promise<DbAdmission> {
    const [row] = await qb(this.db, ctx)
      .insert(admissionsTable)
      .values({ ...data, createdBy: safeUuid(ctx.userId), updatedBy: safeUuid(ctx.userId) })
      .returning();
    return row;
  }

  async update(id: string, data: Partial<InsertAdmission>, ctx: TxContext): Promise<DbAdmission | null> {
    const [row] = await qb(this.db, ctx)
      .update(admissionsTable)
      .set({ ...data, updatedAt: new Date(), updatedBy: safeUuid(ctx.userId) })
      .where(and(eq(admissionsTable.id, id), isNull(admissionsTable.deletedAt)))
      .returning();
    return row ?? null;
  }

  async discharge(id: string, payload: DischargePayload, ctx: TxContext): Promise<DbAdmission | null> {
    const [row] = await qb(this.db, ctx)
      .update(admissionsTable)
      .set({
        status:              "discharged",
        actualDischargeDate: payload.actualDischargeDate,
        actualDischargeTime: payload.actualDischargeTime,
        dischargeType:       payload.dischargeType as any,
        dischargeNotes:      payload.dischargeNotes,
        updatedAt:           new Date(),
        updatedBy:           safeUuid(ctx.userId),
      })
      .where(and(eq(admissionsTable.id, id), isNull(admissionsTable.deletedAt)))
      .returning();
    return row ?? null;
  }

  async softDelete(id: string, ctx: TxContext): Promise<boolean> {
    const [row] = await qb(this.db, ctx)
      .update(admissionsTable)
      .set({ deletedAt: new Date(), deletedBy: safeUuid(ctx.userId) })
      .where(and(eq(admissionsTable.id, id), isNull(admissionsTable.deletedAt)))
      .returning({ id: admissionsTable.id });
    return !!row;
  }
}
