/**
 * EncounterRepository — CRUD for the encounters table.
 * Encounter numbers are generated by EncounterService.
 */
import { eq, and, isNull, desc, count, sql } from "drizzle-orm";
import {
  db as globalDb, encountersTable, type DbEncounter, type InsertEncounter,
} from "@workspace/db";
import { type TxContext, type QueryOptions, type PagedResult, paged, qb , safeUuid } from "./types";

export type { DbEncounter };

export interface EncounterListOpts extends QueryOptions {
  patientId?: string;
  status?:    string;
  type?:      string;
  siteId?:    string;
}

export class EncounterRepository {
  constructor(private readonly db: typeof globalDb = globalDb) {}

  async findById(id: string, ctx?: Pick<TxContext, "tx">): Promise<DbEncounter | null> {
    const rows = await qb(this.db, ctx)
      .select().from(encountersTable)
      .where(and(eq(encountersTable.id, id), isNull(encountersTable.deletedAt)))
      .limit(1);
    return rows[0] ?? null;
  }

  async findByNumber(encounterNumber: string, ctx?: Pick<TxContext, "tx">): Promise<DbEncounter | null> {
    const rows = await qb(this.db, ctx)
      .select().from(encountersTable)
      .where(and(eq(encountersTable.encounterNumber, encounterNumber), isNull(encountersTable.deletedAt)))
      .limit(1);
    return rows[0] ?? null;
  }

  async list(opts: EncounterListOpts = {}): Promise<PagedResult<DbEncounter>> {
    const { patientId, status, type, siteId, limit = 50, offset = 0, includeDeleted = false } = opts;
    const conditions = [];
    if (!includeDeleted) conditions.push(isNull(encountersTable.deletedAt));
    if (patientId)       conditions.push(eq(encountersTable.patientId, patientId));
    if (status)          conditions.push(eq(encountersTable.status, status as any));
    if (type)            conditions.push(eq(encountersTable.type, type as any));
    if (siteId)          conditions.push(eq(encountersTable.siteId, siteId));

    const where = conditions.length ? and(...conditions) : undefined;
    const [rows, [{ total }]] = await Promise.all([
      this.db.select().from(encountersTable).where(where)
        .orderBy(desc(encountersTable.openedAt)).limit(limit).offset(offset),
      this.db.select({ total: count() }).from(encountersTable).where(where),
    ]);
    return paged(rows, Number(total), { limit, offset });
  }

  /** Count all encounters — used by EncounterService to generate next ENC number */
  async countAll(): Promise<number> {
    const [{ total }] = await this.db
      .select({ total: count() }).from(encountersTable);
    return Number(total);
  }

  async create(data: InsertEncounter, ctx: TxContext): Promise<DbEncounter> {
    const [row] = await qb(this.db, ctx)
      .insert(encountersTable)
      .values({ ...data, createdBy: safeUuid(ctx.userId), updatedBy: safeUuid(ctx.userId) })
      .returning();
    return row;
  }

  async update(id: string, data: Partial<InsertEncounter>, ctx: TxContext): Promise<DbEncounter | null> {
    const [row] = await qb(this.db, ctx)
      .update(encountersTable)
      .set({ ...data, updatedAt: new Date(), updatedBy: safeUuid(ctx.userId) })
      .where(and(eq(encountersTable.id, id), isNull(encountersTable.deletedAt)))
      .returning();
    return row ?? null;
  }

  async close(id: string, reason: string, ctx: TxContext): Promise<DbEncounter | null> {
    const [row] = await qb(this.db, ctx)
      .update(encountersTable)
      .set({ status: "closed", closedAt: new Date(), closeReason: reason, updatedBy: safeUuid(ctx.userId) })
      .where(and(eq(encountersTable.id, id), isNull(encountersTable.deletedAt)))
      .returning();
    return row ?? null;
  }

  async appendLinkedRecord(
    id: string,
    record: { recordType: string; recordId: string; summary: string },
    ctx: TxContext,
  ): Promise<void> {
    await qb(this.db, ctx)
      .update(encountersTable)
      .set({
        linkedRecords: sql`jsonb_append(COALESCE(linked_records, '[]'::jsonb), ${JSON.stringify({ ...record, createdAt: new Date().toISOString() })}::jsonb)`,
        updatedBy: safeUuid(ctx.userId),
      })
      .where(eq(encountersTable.id, id));
  }
}
