-- =============================================================================
-- Migration 003 — Schema Additions: MRN, Encounter Number, Attachments,
--                 User Activity Logs
-- =============================================================================
-- Run after 001_clinical_schema.sql and 002_seed_indexes.sql.
-- All statements are idempotent (IF NOT EXISTS / ADD COLUMN IF NOT EXISTS).
-- =============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- 1. MRN on patients
--    Permanent, hospital-scoped Medical Record Number.
--    Format: MRN-YYYY-NNNNN  (generated by PatientService, never recycled).
--    mpi_id remains the cross-facility index; mrn is per-hospital.
-- ---------------------------------------------------------------------------

ALTER TABLE patients
  ADD COLUMN IF NOT EXISTS mrn TEXT;

-- Back-fill from mpi_id for existing rows (replace with real MRN gen in app)
UPDATE patients SET mrn = 'MRN-' || SUBSTRING(mpi_id FROM 5) WHERE mrn IS NULL;

ALTER TABLE patients
  ALTER COLUMN mrn SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_patients_mrn ON patients(mrn);

-- ---------------------------------------------------------------------------
-- 2. Encounter Number on encounters
--    Unique human-readable identifier: ENC-2026-00001.
--    Generated by EncounterService on creation; never recycled.
-- ---------------------------------------------------------------------------

ALTER TABLE encounters
  ADD COLUMN IF NOT EXISTS encounter_number TEXT;

-- Back-fill for existing rows
UPDATE encounters
  SET encounter_number = 'ENC-LEGACY-' || SUBSTRING(CAST(id AS TEXT), 1, 8)
  WHERE encounter_number IS NULL;

ALTER TABLE encounters
  ALTER COLUMN encounter_number SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_encounters_number ON encounters(encounter_number);

-- Denormalized patient MRN for fast display without join
ALTER TABLE encounters
  ADD COLUMN IF NOT EXISTS patient_mrn TEXT;

-- ---------------------------------------------------------------------------
-- 3. Enum types for attachments and user activity
-- ---------------------------------------------------------------------------

DO $$ BEGIN
  CREATE TYPE attachment_entity_type AS ENUM (
    'patient', 'encounter', 'admission', 'consultation',
    'lab_order', 'imaging_order', 'prescription', 'surgical_request', 'invoice'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE attachment_category AS ENUM (
    'report', 'image', 'consent', 'identity',
    'prescription', 'result', 'administrative', 'other'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE user_activity_action AS ENUM (
    'login', 'logout', 'session_expired', 'password_changed',
    'navigate', 'view', 'search', 'filter',
    'print', 'export', 'download', 'generate_pdf',
    'access_denied', 'impersonate'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ---------------------------------------------------------------------------
-- 4. Attachments table (generic / polymorphic)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS attachments (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Polymorphic link
  entity_type   attachment_entity_type NOT NULL,
  entity_id     UUID NOT NULL,

  -- Source module
  module        source_module NOT NULL,

  -- File metadata
  file_name     TEXT NOT NULL,
  file_size     INTEGER,            -- bytes
  mime_type     TEXT NOT NULL,
  category      attachment_category NOT NULL DEFAULT 'other',

  -- Object storage
  storage_key   TEXT NOT NULL,      -- e.g. attachments/2026/07/uuid.pdf
  storage_url   TEXT,               -- Signed URL (regenerated on read, short-lived)

  -- Display
  title         TEXT,
  description   TEXT,
  page_count    INTEGER,

  -- Access
  is_private    BOOLEAN NOT NULL DEFAULT false,

  -- Site
  site_id       UUID REFERENCES sites(id) ON DELETE SET NULL,

  -- Audit (no soft-delete — mark deleted_at to hide, keep storage_key for cleanup)
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by    UUID REFERENCES users(id) ON DELETE SET NULL,
  created_by_name TEXT,
  deleted_at    TIMESTAMPTZ,
  deleted_by    UUID REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_att_entity   ON attachments(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_att_module   ON attachments(module);
CREATE INDEX IF NOT EXISTS idx_att_category ON attachments(category);
CREATE INDEX IF NOT EXISTS idx_att_site     ON attachments(site_id);
CREATE INDEX IF NOT EXISTS idx_att_created  ON attachments(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_att_deleted  ON attachments(deleted_at) WHERE deleted_at IS NULL;

-- ---------------------------------------------------------------------------
-- 5. User Activity Logs (append-only, UI interactions, NOT data mutations)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS user_activity_logs (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  timestamp     TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Actor
  user_id       UUID REFERENCES users(id) ON DELETE SET NULL,
  user_name     TEXT NOT NULL,
  user_role     TEXT NOT NULL,

  -- Action
  action        user_activity_action NOT NULL,

  -- Context
  module        source_module NOT NULL,
  resource_type TEXT,
  resource_id   TEXT,
  resource_label TEXT,

  -- Details
  description   TEXT,
  search_query  TEXT,
  metadata      JSONB,

  -- Request
  ip            TEXT,
  user_agent    TEXT,
  session_id    TEXT,

  -- Site
  site_id       UUID REFERENCES sites(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_ual_timestamp ON user_activity_logs(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_ual_user      ON user_activity_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_ual_action    ON user_activity_logs(action);
CREATE INDEX IF NOT EXISTS idx_ual_module    ON user_activity_logs(module);
CREATE INDEX IF NOT EXISTS idx_ual_resource  ON user_activity_logs(resource_type, resource_id);
CREATE INDEX IF NOT EXISTS idx_ual_session   ON user_activity_logs(session_id);
CREATE INDEX IF NOT EXISTS idx_ual_site      ON user_activity_logs(site_id);

COMMIT;
